#This file was originally generated by PyScripter's unitest wizard

import unittest
import Tensor

class Test_Index(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testsize(self):
        pass

    def testindex_pool(self):
        pass

class TestTensor(unittest.TestCase):

    def setUp(self):
        ip = Tensor.IndexPool
        (i,j) = (ip('ii',3),ip('jj',4))
        self.T = Tensor.Tensor(i,j)

    def tearDown(self):
        pass

    def testset_index(self):
        pass

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexPool(self):
        indexes = []
        for i in range(1,28):
          index = Tensor.IndexPool(size=i)
          self.assertEqual(index.size,i)
        index = Tensor.IndexPool(size=5)
        self.assertEqual(index.size,5)

if __name__ == '__main__':
    unittest.main()
